### ISSUE TITLE
Bug - missing dist folder in node_modules folder when run command yarn add luffie

### ISSUE THREAD

**Issue by danilo-teixeira** [tegraoss/luffie#16]
![image](https://user-images.githubusercontent.com/2219399/66708282-6fb13200-ed24-11e9-9718-a03e98b1a847.png)

**Comment by filipeversehgi** [comment]
Thanks for pointing that issue.
It's already correct in release 0.3.0.

https://codesandbox.io/s/luffie-example-fkobj

**Comment by filipeversehgi** [comment]
Thanks for pointing that issue.
It's already correct in release 0.3.0.

https://codesandbox.io/s/luffie-example-fkobj
